openapi: 3.0.1
info:
  title: Rest API Docs
  description: Authors
  version: 1.0.0
paths:
  /authors/:
    get:
      tags:
        - Authors
      summary: List all available authors
      responses:
        200:
          description: A list of authors.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "difinitions.yaml#/components/schemas/Author"
        500:
          description: Unexpected Error
    post:
      tags:
        - Authors
      summary: Add a new author
      requestBody:
        description: Author create request
        content:
          application/json:
            schema:
              $ref: "difinitions.yaml#/components/schemas/CreateAuthor"
        required: true
      responses:
        201:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "difinitions.yaml#/components/schemas/Author"
        400:
          description: Invalid request provided
        500:
          description: Unexpected Error
    put:
      tags:
        - Authors
      summary: Update author
      requestBody:
        description: Author update request
        content:
          application/json:
            schema:
              $ref: "difinitions.yaml#/components/schemas/Author"
        required: true
      responses:
        200:
          description: Successful operation
        400:
          description: Invalid request provided
        500:
          description: Unexpected Error

  /authors/{id}:
    get:
      tags:
        - Authors
      summary: Get author
      parameters:
        - in: path
          name: id
          required: true
          schema: 
            type: integer
      responses:
        200:
          description: get author by id
          content:
            application/json:
              schema:
                $ref: "difinitions.yaml#/components/schemas/Author"
        500:
          description: Unexpected Error
    delete:
      tags:
        - Authors
      summary: Delete author
      parameters:
        - in: path
          name: id
          required: true
          schema: 
            type: integer
          description: Author delete request
      responses:
        200:
          description: Successful operation
        400:
          description: Invalid request provided
        500:
          description: Unexpected Error