openapi: 3.0.0
info:
  title: Definitions
  version: 1.0.0
paths: {}

components:
  parameters:
    # Paging offset
    OffsetParam:
      name: offset
      required: false
      in: query
      description: Paging offset
      schema:
        type: integer
        minimum: 0
        multipleOf: 10
        default: 0
    # Page size
    LimitParam:
      name: limit
      required: false
      in: query
      description: Paging limit
      schema:
        type: integer
        minimum: 10
        maximum: 1000
        multipleOf: 10
        default: 20
  schemas:
    Category:
      allOf:
        - $ref: '#/components/schemas/CreateCategory'
        - type: object
          properties:
            id: 
              type: integer
          required:
            - id

    CreateCategory:
      type: object
      properties:
        parentCategoryId:
          nullable: true
          type: integer
        label: 
          type: string
      required:
        - label
        - parentCategoryId

    Login:
      type: object
      properties:
        username:
          type: string
          example: userLogin    
        password:
          type: string
          example: 123    
      required:
        - username
        - password
        
    UserModel:
      allOf:
        - $ref: '#/components/schemas/BaseUser'
        - type: object
          properties:
            passwordHash: 
              type: string
            id:
              type: integer
            tokenCounter:
              type: integer
            isAdmin:
              type: boolean
          required:
            - passwordHash
            - id
            - tokenCounter
            - isAdmin
    UserView:
      allOf:
        - $ref: '#/components/schemas/BaseUser'
        - type: object
          properties:
            id:
              type: integer
            isAdmin:
              type: boolean
          required:
            - id
            - isAdmin

    CreateUser:
      allOf:
        - $ref: '#/components/schemas/BaseUser'
        - type: object
          properties:
            password: 
              type: string
          required:
            - password


    BaseUser:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        avatarUrl:
          type: string
      required:
        - username
        - firstName
        - lastName
        - avatarUrl

    Author:
      allOf:
        - $ref: '#/components/schemas/CreateAuthor'
        - type: object
          properties:
            id: 
              type: integer
          required:
            - id


    CreateAuthor:
      type: object
      properties:
        userId:
          type: integer
        description:
          type: string
      required:
        - userId
        - description
        