openapi: 3.0.1
info:
  title: Rest API Docs
  description: MetaNews is a news site
  version: 1.0.0
paths:
  /categories/:
    get:
      tags:
        - Category
      summary: All available categories
      responses:
        '200':
          description: A list of categories.
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - type: object
                      properties:
                        parentCategoryId:
                          nullable: true
                          type: integer
                        label:
                          type: string
                      required:
                        - label
                        - parentCategoryId
                    - type: object
                      properties:
                        id:
                          type: integer
                      required:
                        - id
        '500':
          description: Unexpected Error
    post:
      tags:
        - Category
      summary: Add a new category
      security:
        - cookieAuth: []
      requestBody:
        description: Category create request (available only for admins)
        content:
          application/json:
            schema:
              type: object
              properties:
                parentCategoryId:
                  nullable: true
                  type: integer
                label:
                  type: string
              required:
                - label
                - parentCategoryId
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      parentCategoryId:
                        nullable: true
                        type: integer
                      label:
                        type: string
                    required:
                      - label
                      - parentCategoryId
                  - type: object
                    properties:
                      id:
                        type: integer
                    required:
                      - id
        '400':
          description: Invalid request provided
        '500':
          description: Unexpected Error
    put:
      tags:
        - Category
      summary: Update category
      security:
        - cookieAuth: []
      requestBody:
        description: Category update request (available only for admins)
        content:
          application/json:
            schema:
              allOf:
                - type: object
                  properties:
                    parentCategoryId:
                      nullable: true
                      type: integer
                    label:
                      type: string
                  required:
                    - label
                    - parentCategoryId
                - type: object
                  properties:
                    id:
                      type: integer
                  required:
                    - id
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid request provided
        '500':
          description: Unexpected Error
  '/categories/{id}':
    delete:
      security:
        - cookieAuth: []
      tags:
        - Category
      summary: Delete category (available only for admins)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Category delete request
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid request provided
        '500':
          description: Unexpected Error
  /users/:
    get:
      tags:
        - Users
      summary: List all users (available only for admins)
      security:
        - cookieAuth: []
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - type: object
                      properties:
                        username:
                          type: string
                        firstName:
                          type: string
                        lastName:
                          type: string
                        avatarUrl:
                          type: string
                      required:
                        - username
                        - firstName
                        - lastName
                        - avatarUrl
                    - type: object
                      properties:
                        id:
                          type: integer
                        isAdmin:
                          type: boolean
                      required:
                        - id
                        - isAdmin
        '401':
          description: Not authorized
        '500':
          description: Unexpected Error
    post:
      tags:
        - Users
      summary: Add a new user
      requestBody:
        description: User create request
        content:
          application/json:
            schema:
              allOf:
                - type: object
                  properties:
                    username:
                      type: string
                    firstName:
                      type: string
                    lastName:
                      type: string
                    avatarUrl:
                      type: string
                  required:
                    - username
                    - firstName
                    - lastName
                    - avatarUrl
                - type: object
                  properties:
                    password:
                      type: string
                  required:
                    - password
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      username:
                        type: string
                      firstName:
                        type: string
                      lastName:
                        type: string
                      avatarUrl:
                        type: string
                    required:
                      - username
                      - firstName
                      - lastName
                      - avatarUrl
                  - type: object
                    properties:
                      id:
                        type: integer
                      isAdmin:
                        type: boolean
                    required:
                      - id
                      - isAdmin
        '400':
          description: Invalid request provided
        '500':
          description: Unexpected Error
    patch:
      tags:
        - Users
      summary: Update user (available only for admins)
      security:
        - cookieAuth: []
      requestBody:
        description: User update request
        content:
          application/json:
            schema:
              allOf:
                - type: object
                  properties:
                    username:
                      type: string
                    firstName:
                      type: string
                    lastName:
                      type: string
                    avatarUrl:
                      type: string
                  required:
                    - username
                    - firstName
                    - lastName
                    - avatarUrl
                - type: object
                  properties:
                    id:
                      type: integer
                    isAdmin:
                      type: boolean
                  required:
                    - id
                    - isAdmin
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid request provided
        '500':
          description: Unexpected Error
  '/users/{id}':
    delete:
      tags:
        - Users
      summary: Delete user (available only for admins)
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: User delete request
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid request provided
        '500':
          description: Unexpected Error
  /users/me:
    get:
      tags:
        - Users
      summary: Get my user
      security:
        - cookieAuth: []
      responses:
        '200':
          description: get user
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      username:
                        type: string
                      firstName:
                        type: string
                      lastName:
                        type: string
                      avatarUrl:
                        type: string
                    required:
                      - username
                      - firstName
                      - lastName
                      - avatarUrl
                  - type: object
                    properties:
                      id:
                        type: integer
                      isAdmin:
                        type: boolean
                    required:
                      - id
                      - isAdmin
        '500':
          description: Unexpected Error
  /users/login/:
    post:
      tags:
        - Users
      summary: authoriztion
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: userLogin
                password:
                  type: string
                  example: 123
              required:
                - username
                - password
        required: true
      responses:
        '200':
          description: Authorized
          headers:
            Set-Cookie:
              schema:
                type: string
                example: JWT=abcde12345; Path=/; HttpOnly
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      username:
                        type: string
                      firstName:
                        type: string
                      lastName:
                        type: string
                      avatarUrl:
                        type: string
                    required:
                      - username
                      - firstName
                      - lastName
                      - avatarUrl
                  - type: object
                    properties:
                      id:
                        type: integer
                      isAdmin:
                        type: boolean
                    required:
                      - id
                      - isAdmin
        '400':
          description: Invalid request provided
        '500':
          description: Unexpected Error
  /authors/:
    get:
      tags:
        - Authors
      summary: List all available authors (available only for admins)
      security:
        - cookieAuth: []
      responses:
        '200':
          description: A list of authors.
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - type: object
                      properties:
                        userId:
                          type: integer
                        description:
                          type: string
                      required:
                        - userId
                        - description
                    - type: object
                      properties:
                        id:
                          type: integer
                      required:
                        - id
        '500':
          description: Unexpected Error
    post:
      tags:
        - Authors
      summary: Add a new author (available only for admins)
      security:
        - cookieAuth: []
      requestBody:
        description: Author create request
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                description:
                  type: string
              required:
                - userId
                - description
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      userId:
                        type: integer
                      description:
                        type: string
                    required:
                      - userId
                      - description
                  - type: object
                    properties:
                      id:
                        type: integer
                    required:
                      - id
        '400':
          description: Invalid request provided
        '500':
          description: Unexpected Error
    put:
      tags:
        - Authors
      summary: Update author (available only for admins)
      security:
        - cookieAuth: []
      requestBody:
        description: Author update request
        content:
          application/json:
            schema:
              allOf:
                - type: object
                  properties:
                    userId:
                      type: integer
                    description:
                      type: string
                  required:
                    - userId
                    - description
                - type: object
                  properties:
                    id:
                      type: integer
                  required:
                    - id
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid request provided
        '500':
          description: Unexpected Error
  '/authors/{id}':
    get:
      tags:
        - Authors
      summary: Get author (available only for admins)
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: get author by id
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      userId:
                        type: integer
                      description:
                        type: string
                    required:
                      - userId
                      - description
                  - type: object
                    properties:
                      id:
                        type: integer
                    required:
                      - id
        '500':
          description: Unexpected Error
    delete:
      tags:
        - Authors
      summary: Delete author (available only for admins)
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Author delete request
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid request provided
        '500':
          description: Unexpected Error
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: jwt
