openapi: 3.0.1
info:
  title: NewSite Rest API
  description: Categories
  version: 1.0.0
paths:
  /categories/:
    $ref: 'categories.yaml#/paths/~1categories~1'
  /categories/{id}:
    $ref: 'categories.yaml#/paths/~1categories~1{id}'