openapi: 3.0.1
info:
  title: Rest API Docs
  description: MetaNews is a news site
  version: 1.0.0
paths:
  /categories/:
    $ref: 'categories.yaml#/paths/~1categories~1'
  /categories/{id}:
    $ref: 'categories.yaml#/paths/~1categories~1{id}'
  /users/:
    $ref: 'users.yaml#/paths/~1users~1'
  /users/{id}:
    $ref: 'users.yaml#/paths/~1users~1{id}'
  /users/me:
    $ref: 'users.yaml#/paths/~1users~1me'
  /users/login/:
    $ref: 'users.yaml#/paths/~1users~1login~1'
  /authors/:
    $ref: 'authors.yaml#/paths/~1authors~1'
  /authors/{id}:
    $ref: 'authors.yaml#/paths/~1authors~1{id}'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: jwt