openapi: 3.0.1
info:
  title: NewSite Rest API
  description: News
  version: 1.0.0
paths:
  /posts/:
    get:
      tags:
        - News
      summary: All available news
      responses:
        200:
          description: A list of news.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "difinitions.yaml#/components/schemas/FullNews"
        500:
          description: Unexpected Error
    post:
      tags:
        - News
      summary: Add a new News
      security:
        - cookieAuth: []
      requestBody:
        description: News create request
        content:
          application/json:
            schema:
              $ref: "difinitions.yaml#/components/schemas/CreateNews"
        required: true
      responses:
        201:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "difinitions.yaml#/components/schemas/News"
        400:
          description: Invalid request provided
        500:
          description: Unexpected Error
    patch:
      tags:
        - News
      summary: Update News
      security:
        - cookieAuth: []
      requestBody:
        description: News update request
        content:
          application/json:
            schema:
              $ref: "difinitions.yaml#/components/schemas/News"
        required: true
      responses:
        200:
          description: Successful operation
        400:
          description: Invalid request provided
        500:
          description: Unexpected Error

  /posts/{id}:
    get:
      tags:
        - News
      responses:
        200:
          description: One post.
          content:
            application/json:
              schema:
               $ref: "difinitions.yaml#/components/schemas/FullNews"
        500:
          description: Unexpected Error
    delete:
      security:
        - cookieAuth: []
      tags:
        - News
      summary: Delete News (available only for admins)
      parameters:
        - in: path
          name: id
          required: true
          schema: 
            type: integer
          description: News delete request
      responses:
        200:
          description: Successful operation
        400:
          description: Invalid request provided
        500:
          description: Unexpected Error