openapi: 3.0.1
info:
  title: Rest API Docs
  description: Users
  version: 1.0.0
paths:
  /users/:
    get:
      tags:
        - Users
      summary: List all available users
      responses:
        200:
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "difinitions.yaml#/components/schemas/User"
        500:
          description: Unexpected Error
    post:
      tags:
        - Users
      summary: Add a new user
      requestBody:
        description: User create request
        content:
          application/json:
            schema:
              $ref: "difinitions.yaml#/components/schemas/CreateUser"
        required: true
      responses:
        201:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "difinitions.yaml#/components/schemas/User"
        400:
          description: Invalid request provided
        500:
          description: Unexpected Error
    put:
      tags:
        - Users
      summary: Update user
      requestBody:
        description: User update request
        content:
          application/json:
            schema:
              $ref: "difinitions.yaml#/components/schemas/User"
        required: true
      responses:
        200:
          description: Successful operation
        400:
          description: Invalid request provided
        500:
          description: Unexpected Error

  /users/{id}:
    get:
      tags:
        - Users
      summary: Get user
      parameters:
        - in: path
          name: id
          required: true
          schema: 
            type: integer
      responses:
        200:
          description: get user by id
          content:
            application/json:
              schema:
                $ref: "difinitions.yaml#/components/schemas/User"
        500:
          description: Unexpected Error
    delete:
      tags:
        - Users
      summary: Delete user
      parameters:
        - in: path
          name: id
          required: true
          schema: 
            type: integer
          description: User delete request
      responses:
        200:
          description: Successful operation
        400:
          description: Invalid request provided
        500:
          description: Unexpected Error